Fix fatal errors related to anchors.
Bikeshed appears to require an actual anchor in the link, even
when one does not exist on the target page. An empty/unnamed
anchor appears sufficient.

Fixes these errors:
FATAL ERROR: Couldn't find target anchor https://aomediacodec.github.io/av1-spec/av1-spec.pdf:
<a href="#https://aomediacodec.github.io/av1-spec/av1-spec.pdf">#https://aomediacodec.github.io/av1-spec/av1-spec.pdf</a>
FATAL ERROR: Couldn't find target anchor http://iso.org:
<a href="#http://iso.org">#http://iso.org</a>